# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Debug_Server'
  buildPlatform: 'Any CPU'
  ciTime: $[format('{0:yyyyMMddHHmmss}', pipeline.startTime)]
  project: 'BlazorMdc/BlazorMdc.csproj'

steps:


- powershell: 'dotnet build --configuration $(buildConfiguration) $(project)'
  displayName: 'Building $(project) in $(buildConfiguration) mode...'

- powershell: 'dotnet pack --configuration $(buildConfiguration) --no-build --output $(Build.ArtifactStagingDirectory) --version-suffix CI.$(ciTime) $(project)'
  displayName: 'Generating Nuget Package... '

- task: NuGetCommand@2
  displayName: 'Pushing NuGet package to internal feed'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'BlazorMdc'
    allowPackageConflicts: true
