# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: 'BlazorMdc.sln'
  project: 'BlazorMdc/BlazorMdc.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release_Server'

steps:

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'# 
 
- script: dotnet build --configuration $(buildConfiguration) $(project)
  displayName: 'Building $(project) in $(buildConfiguration) mode...'

- task: DotNetCoreCLI@2
  displayName: 'Generating Nuget Package... '
  inputs:
    command: pack
    arguments: --no-build
    packagesToPack: $(project)
    configuration: $(buildConfiguration)
    versioningScheme: 'off'

- task: PublishBuildArtifacts@1
  displayName: 'Publishing Build Artifacts...'

- script: if exist (Build.ArtifactStagingDirectory)/*.nupkg del /q (Build.ArtifactStagingDirectory)/*.nupkg

- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    allowPackageConflicts: true
