# ASP.NET Core (.NET Framework)

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release_Server'
  buildPlatform: 'Any CPU'
  ciYear: $[format('{0:yyyy}', pipeline.startTime)]
  ciMonth: $[format('{0:MM}', pipeline.startTime)]
  ciDay: $[format('{0:dd}', pipeline.startTime)]
  ciHour: $[format('{0:HH}', pipeline.startTime)]
  ciMinute: $[format('{0:mm}', pipeline.startTime)]
  ciSecond: $[format('{0:ss}', pipeline.startTime)]
  project: 'BlazorMdc/BlazorMdc.csproj'

steps:

- powershell: 'Write-Host "##vso[task.setvariable variable=ciSuffix]CI.$(ciYear).$(ciMonth).$(ciDay).$(ciHour).$(ciMinute).$(ciSecond)"'
  displayName: 'Creating CI suffix with powershell'

- task: CmdLine@2
  diaplayName: "Displaying CI suffix"
  inputs:
    script: echo ciSuffix is $(ciSuffix)

- powershell: 'dotnet build --configuration $(buildConfiguration) $(project)'
  displayName: 'Building $(project) in $(buildConfiguration) mode'

- powershell: 'dotnet pack --configuration $(buildConfiguration) --no-build --output $(Build.ArtifactStagingDirectory) --version-suffix $(ciSuffix) $(project)'
  displayName: 'Generating Nuget Package with a CI suffix of $(ciSuffix)'

- task: NuGetCommand@2
  displayName: 'Pushing NuGet package to internal feed'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'BlazorMdc'
    allowPackageConflicts: true
