name: GithubActionsMainCI

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

env:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Debug_Server'
  ciSuffix: CI.${{ github.run_number }}
  outputDocFx: ${{ github.workspace }}\site-docfx
  outputNuget: ${{ github.workspace }}\site-nuget
  outputWeb: ${{ github.workspace }}\site-web
  project: 'BlazorMdc\BlazorMdc.csproj'

jobs:

  builddocfx:

    runs-on: windows-latest

    steps:

    - name: Checkout repository under $GITHUB_WORKSPACE so the job can access it 🛎️
      uses: actions/checkout@v2

    - name: Create documentation 🔧
      run: .\docfx\docfx docfx.json
      env:
        DOCFX_SOURCE_BRANCH_NAME: ${{steps.get_branch.outputs.branch}}
      if: (contains(github.ref, 'refs/heads'))

    - name: Upload Artifacts 🔺 # The project is then uploaded as an artifact named 'site'.
      uses: actions/upload-artifact@v1
      with:
        name: site-docfx
        path: site-docfx
      if: (contains(github.ref, 'refs/heads') && (github.repository != 'BlazorMdc/BlazorMdc'))


  buildblazormdc:
    needs: [builddocfx] # The second job must depend on the first one to complete before running, and uses ubuntu-latest instead of windows.

    runs-on: ubuntu-latest

    steps:

# identify the trigger of the run

    - name: Get the branch
      id: get_branch
      run: echo ::set-output name=branch::${GITHUB_REF/refs\/heads\//}

    - name: Get the pullrequest
      id: get_pullrequest
      run: echo ::set-output name=pullrequest::${GITHUB_REF/refs\/pull\//}

    - name: Get the tag
      id: get_tag
      run: echo ::set-output name=tag::${GITHUB_REF/refs\/tags\//}

    - name: Show branch name Ꙫ
      run: echo "GitHub indicates that this is a branch push request of ${{steps.get_branch.outputs.branch}}"
      if: contains(github.ref, 'refs/heads')

    - name: Show PR name Ꙫ
      run: echo "GitHub indicates that this is a pull request called ${{steps.get_pullrequest.outputs.pullrequest}}"
      if: contains(github.ref, 'refs/pull')

    - name: Show Tag name Ꙫ
      run: echo "GitHub indicates that this is a tag creation with ${{steps.get_tag.outputs.tag}}"
      if: contains(github.ref, 'refs/tag')


#repository checkout is a constant

    - name: Checkout repository under $GITHUB_WORKSPACE so the job can access it 🛎️
      uses: actions/checkout@v2


#deploy docfx pages

    - name: Download Artifacts 🔻 # The built project is downloaded into the 'site' folder.
      uses: actions/download-artifact@v1
      with:
        name: site-ghpages
      if: (contains(github.ref, 'refs/heads') && (github.repository != 'BlazorMdc/BlazorMdc'))

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.GH_PAT }}
        BRANCH: gh-pages
        FOLDER: "site-ghpages" # The deployment folder should match the name of the artifact.
      if: (contains(github.ref, 'refs/heads') && (github.repository != 'BlazorMdc/BlazorMdc'))


#build and deploy BlazorMdc

    - name: Setup .NET Core 🛎️
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.302
        source-url: https://nuget.pkg.github.com/${{github.repository_owner}}/index.json
      env:
        NUGET_AUTH_TOKEN: '%NUGET_AUTH_TOKEN%'

    - name: Display CI suffix Ꙫ
      run: echo "CI suffix is $ciSuffix"

    - name: Build 🔧
      run: dotnet build --configuration $buildConfiguration --version-suffix $ciSuffix $project
      env:
        NUGET_AUTH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

    - name: Generate NuGet package 🔧
      run: dotnet pack --no-build --configuration $buildConfiguration --output $outputNuget -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --version-suffix $ciSuffix $project
      env:
        NUGET_AUTH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

    - name: Display package output Ꙫ
      run: ls $outputNuget

    - name: Display obfuscated secret Ꙫ
      run: echo "The GitHub token is ${{ secrets.GITHUB_TOKEN }}"

    - name: Upload Package 🚀
      run: nuget push $outputnuget\*.nupkg -Source https://nuget.pkg.github.com/${{github.repository_owner}}/index.json
      env:
        NUGET_AUTH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      if: ((github.repository == 'BlazorMdc/BlazorMdc') && (github.event_name == 'push'))


#there are no dependencies for this job so it can run in parallel with the first two
#this has to be a separate job because of the differnt dnc environment

  buildblazormdcwebsite:

    runs-on: ubuntu-latest

    steps:

    - name: Get the branch
      id: get_branch
      run: echo ::set-output name=branch::${GITHUB_REF/refs\/heads\//}

    - name: Get the pullrequest
      id: get_pullrequest
      run: echo ::set-output name=pullrequest::${GITHUB_REF/refs\/pull\//}

    - name: Get the tag
      id: get_tag
      run: echo ::set-output name=tag::${GITHUB_REF/refs\/tags\//}

    - name: Show branch name Ꙫ
      run: echo "GitHub indicates that this is a branch push request of ${{steps.get_branch.outputs.branch}}"
      if: contains(github.ref, 'refs/heads')

    - name: Show PR name Ꙫ
      run: echo "GitHub indicates that this is a pull request called ${{steps.get_pullrequest.outputs.pullrequest}}"
      if: contains(github.ref, 'refs/pull')

    - name: Show Tag name Ꙫ
      run: echo "GitHub indicates that this is a tag creation with ${{steps.get_tag.outputs.tag}}"
      if: contains(github.ref, 'refs/tag')


    - name: Checkout repository under $GITHUB_WORKSPACE so the job can access it 🛎️
      uses: actions/checkout@v2


    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100-preview.7.20366.6

    - name: Build 🔧
      run: dotnet build --configuration $buildConfiguration $project

    - name: Publish 🔧
      run: dotnet publish --no-build --configuration $buildConfiguration --output $outputWeb $project

#Do the href rewrite if we aren't publishing to the 'real' BlazorMdcWebsite

    - name: Base Href Rewrite 👉
      uses: SteveSandersonMS/ghaction-rewrite-base-href@v1
      with:
        html_path: '$outputWeb/wwwroot/index.html'
        base_href: '/BlazorMdcWebsite/'
      if: (contains(github.ref, 'refs/heads') && (github.repository != 'BlazorMdc/BlazorMdc'))

# deploy either to the SZ or MS Website depending on where we are doing the build

    - name: Deploy OHI 🚀
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.GH_PAT }}
        BRANCH: gh-pages
        FOLDER: "$outputWeb/wwwroot"
        REPOSITORY_NAME: 'OptimiumHealth/BlazorMdcWebsite'
      if: (contains(github.ref, 'refs/heads') && (github.repository == 'OptimiumHealth/BlazorMdc'))

    - name: Deploy SZ 🚀
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.GH_PAT }}
        BRANCH: gh-pages
        FOLDER: "$outputWeb/wwwroot"
        REPOSITORY_NAME: 'SimonZiegler/BlazorMdcWebsite'
      if: (contains(github.ref, 'refs/heads') && (github.repository == 'SimonZiegler/BlazorMdc'))
